### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by Falape** [Falape/Projeto_RPCW2023#29]
- [ ] campos de 
- [ ] cena para dar rating
- [ ] diferença entre se foi o user a criar ou não
- [ ] para dar ou não update
- [ ] o admin ver merdas que estão apagadas
- [ ] e dar revive
- [ ] dar aprove the updates de roles
- [ ] dar update de user info
- [ ] ver outros users
- [ ] visualizar os docs de um recurso
- [ ] se conseguíssemos (que é um requisito) o type dos recursos
- [ ] filtro para os recursos
- [ ] noticias
- [ ] autentificação com outras plataformas
- [ ] lista de updateRolesrequest, que ainda tenho de alterar na API para apagar depois de aceite
- [ ] ainda dar erros bonitos e não estouros ou página de erros

no final:
-> depois por isto qq coisa mais bonita 
-> testar
-> criar exmplo

**Comment by AROM98** [comment]
isto está muito fixe, boa ideia!!
